### ISSUE TITLE
Enhanced Error module

### ISSUE THREAD

**Issue by aparajita** [gulpjs/gulp#1329]
In gulp 3, when errors were logged the output was colored nicely, with separate colors for filenames, plugin name, etc. Now **everything** is red, which is quite hard to look at and to parse visually.

In addition, we get "Details" which look like this:

```
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

Not especially helpful.

Were these changes by design, or is it something that should be fixed?

**Comment by phated** [comment]
This is due to thrown errors being caught using domains.  Please post screenshots of before/after for the colors?

**Comment by phated** [comment]
Pinging thread for the requested information.

**Comment by aparajita** [comment]
Colors seem to be okay now. But the useless details remain.

**Comment by aparajita** [comment]
If `domainThrown: false`, it seems to me that anything related to domains in the details should be removed, and if there is nothing left after removing domains, details can be skipped.

**Comment by phated** [comment]
I completely disagree that the domain information should be thrown away.  Nothing changed in the color.  I don't think there is anything to do here.

**Comment by aparajita** [comment]
I'm not ranting, but from a user's perspective it might as well say this:

```
Details:
    domainEmitter: [Totally useless info]
    domain: [Totally useless info]
    domainThrown: false (and since there's no useful info about the actual domain, this is useless as well)
```

What is it actually telling the user if the values are hidden?
